export const COLORS = [
  "#FA982A", "#F9C43B", "#E88873", "#FE5B62", "#A54D53",
  "#E840E1", "#EA25A7", "#831985", "#A6009F", "#73CDFF",
  "#25A3EA", "#006AA6", "#3B708D", "#6CAD9D", "#0DA666",
  "#B5446E", "#13505B", "#FF7A00", "#48A9A6"
];

export const ICONS = [
  "ambulance",
  "beer",
  "book",
  "building",
  "cake-wedding",
  "calendar",
  "car",
  "carrot",
  "chart-pie-alt",
  "coffee",
  "credit-card",
  "croissant",
  "diamond",
  "edit",
  "film",
  "folder",
  "gas-pump",
  "graduation-cap",
  "gift",
  "guitar",
  "hamburger",
  "hand-holding-heart",
  "heart",
  "home",
  "lipstick",
  "money",
  "paper-plane",
  "palette",
  "paw",
  "pencil",
  "picture",
  "ping-pong",
  "pizza-slice",
  "plane",
  "shield-plus",
  "shopping-cart",
  "stethoscope",
  "thumbtack",
  "user",
  "utensils",
];
